name = "ellebi-it"
type = "javascript"
main = "src/index.js"
compatibility_date = "2024-01-01"

[build]
command = ""
watch_paths = ["assets/**/*", "*.html", "*.txt", "*.xml", "*.webmanifest", "*.svg"]

[env.production]
name = "ellebi-it-prod"
routes = [
  { pattern = "ellebi.it/*", zone_name = "ellebi.it" },
  { pattern = "www.ellebi.it/*", zone_name = "ellebi.it" }
]
